export const response = {
  data: [
    {
      location_id: "17638605",
      name: "Guest House Thanh Binh",
      latitude: "12.28163",
      longitude: "108.92137",
      num_reviews: "0",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Khanh Vinh, Khanh Hoa Province",
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      ranking_position: "1",
      ranking_denominator: "1711",
      ranking: "#1 Best Value of 1,711 places to stay in Nha Trang",
      distance: "8.567854322550199",
      distance_string: null,
      bearing: "southeast",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "188d753c-ce15-4dc3-9489-46dc2fc85c27",
    },
    {
      location_id: "23515930",
      name: "Phan Gia Xanh Garden",
      latitude: "12.299181",
      longitude: "108.99182",
      num_reviews: "0",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Dien Khanh, Khanh Hoa Province",
      photo: {
        images: {
          small: {
            width: "137",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/27/42/cd/31/phan-gia-xanh-khu-tr.jpg",
            height: "205",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/27/42/cd/31/phan-gia-xanh-khu-tr.jpg",
            height: "50",
          },
          original: {
            width: "1024",
            url: "https://media-cdn.tripadvisor.com/media/photo-w/27/42/cd/31/phan-gia-xanh-khu-tr.jpg",
            height: "1536",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-p/27/42/cd/31/phan-gia-xanh-khu-tr.jpg",
            height: "825",
          },
          medium: {
            width: "300",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/27/42/cd/31/phan-gia-xanh-khu-tr.jpg",
            height: "450",
          },
        },
        is_blessed: false,
        uploaded_date: "2022-12-09T22:17:30-0500",
        caption:
          "PHAN GIA XANH – khu trải nghiệm văn hóa và du lịch sinh thái độc đáo, tách biệt khỏi sự ồn ã của đô thị là gợi ý thích hợp dành cho bạn để cảm xúc chạm vào thiên nhiên. Như một món quà ban tặng để bạn tìm thấy nhịp điệu trong tâm hồn, sống chậm lại, thư giãn và kết nối với chính mình.",
        id: "658689329",
        helpful_votes: "1",
        published_date: "2022-12-09T22:17:30-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      ranking_position: "2",
      ranking_denominator: "1711",
      ranking: "#2 Best Value of 1,711 places to stay in Nha Trang",
      distance: "12.572358417278044",
      distance_string: null,
      bearing: "east",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "aded3c2d-303e-4b8c-9ab9-9ffc67170763",
    },
    {
      location_id: "15574313",
      name: "Farmer's Resort",
      latitude: "12.26634",
      longitude: "108.99182",
      num_reviews: "0",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Dien Thọ, Khanh Hoa Province",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/16/a2/13/c4/across-river.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/16/a2/13/c4/across-river.jpg",
            height: "50",
          },
          original: {
            width: "1280",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/16/a2/13/c4/across-river.jpg",
            height: "960",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/16/a2/13/c4/across-river.jpg",
            height: "413",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/16/a2/13/c4/across-river.jpg",
            height: "188",
          },
        },
        is_blessed: true,
        uploaded_date: "2019-03-02T10:12:31-0500",
        caption: "across river",
        id: "379720644",
        helpful_votes: "0",
        published_date: "2019-03-02T10:12:31-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      ranking_position: "3",
      ranking_denominator: "1711",
      ranking: "#3 Best Value of 1,711 places to stay in Nha Trang",
      distance: "13.305339743048233",
      distance_string: null,
      bearing: "southeast",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "7c8d1f92-bc91-4e51-a2b6-ad3fbdc5e885",
    },
    {
      location_id: "24973203",
      name: "Selectum Noa Resort Cam Ranh",
      latitude: "12.238023",
      longitude: "109.01642",
      num_reviews: "4",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Nha Trang, Khanh Hoa Province",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/2a/92/e8/46/caption.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/2a/92/e8/46/caption.jpg",
            height: "50",
          },
          original: {
            width: "1280",
            url: "https://media-cdn.tripadvisor.com/media/photo-m/1280/2a/92/e8/46/caption.jpg",
            height: "1038",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/2a/92/e8/46/caption.jpg",
            height: "446",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/2a/92/e8/46/caption.jpg",
            height: "203",
          },
        },
        is_blessed: false,
        uploaded_date: "2023-10-13T06:13:15-0400",
        caption: "",
        id: "714270790",
        helpful_votes: "0",
        published_date: "2023-10-13T06:13:15-0400",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      raw_ranking: "3.1426870822906494",
      ranking_geo: "Nha Trang",
      ranking_geo_id: "293928",
      ranking_position: "4",
      ranking_denominator: "1711",
      ranking_category: "hotel",
      ranking: "#4 Best Value of 1,711 places to stay in Nha Trang",
      subcategory_type: "resort",
      subcategory_type_label: "Resort",
      distance: "15.652667330236172",
      distance_string: null,
      bearing: "southeast",
      rating: "5.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "112ea005-681f-42f9-9059-acd82404b5f6",
    },
    {
      location_id: "26678295",
      name: "Olivia Hotel and Apartment",
      latitude: "12.238023",
      longitude: "109.01642",
      num_reviews: "0",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Nha Trang, Khanh Hoa Province",
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      ranking_position: "5",
      ranking_denominator: "1711",
      ranking: "#5 Best Value of 1,711 places to stay in Nha Trang",
      distance: "15.652667330236172",
      distance_string: null,
      bearing: "southeast",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "64f8f35f-5934-419f-bab7-bd40ef1df61a",
    },
    {
      location_id: "1114960",
      name: "Memento Country Home",
      latitude: "12.252678",
      longitude: "109.06523",
      num_reviews: "29",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Dien Hoa, Khanh Hoa Province",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/0a/51/0c/eb/the-mainson.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/0a/51/0c/eb/the-mainson.jpg",
            height: "50",
          },
          original: {
            width: "1000",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/0a/51/0c/eb/the-mainson.jpg",
            height: "562",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/0a/51/0c/eb/the-mainson.jpg",
            height: "309",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/0a/51/0c/eb/the-mainson.jpg",
            height: "141",
          },
        },
        is_blessed: true,
        uploaded_date: "2016-02-13T20:46:01-0500",
        caption: "The Mainson",
        id: "173083883",
        helpful_votes: "0",
        published_date: "2016-02-13T20:46:01-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      raw_ranking: "3.1579177379608154",
      ranking_geo: "Dien Hoa",
      ranking_geo_id: "26343680",
      ranking_position: "6",
      ranking_denominator: "1711",
      ranking_category: "bb",
      ranking: "#6 Best Value of 1,711 places to stay in Nha Trang",
      subcategory_type: "small_hotel",
      subcategory_type_label: "Small Hotel",
      distance: "18.26603614785037",
      distance_string: null,
      bearing: "east",
      rating: "4.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$20 - $25",
      hotel_class: "3.0",
      hotel_class_attribution:
        "This property is classified according to Giata.",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "2913d357-a8e0-4887-82b0-e35fa5b0f192",
    },
    {
      location_id: "293928",
      ad_position: "inline1",
      ad_size: "8X8",
      doubleclick_zone: "as.vietnam.khanh_hoa.nha_trang",
      ancestors: [
        {
          subcategory: [
            {
              key: "province",
              name: "Province",
            },
          ],
          name: "Khanh Hoa Province",
          abbrv: null,
          location_id: "1184689",
        },
        {
          subcategory: [
            {
              key: "country",
              name: "Country",
            },
          ],
          name: "Vietnam",
          abbrv: null,
          location_id: "293921",
        },
      ],
      detail: "0",
      page_type: "hotels",
      mob_ptype: "app_hotels",
    },
    {
      location_id: "16667354",
      name: "Chappi Mountains Homestay Bungalows & Coffee Resting Station",
      latitude: "12.140835",
      longitude: "108.631775",
      num_reviews: "4",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Lac Duong, Lam Dong Province",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/17/02/4b/1c/chappi-mountains-resort.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/17/02/4b/1c/chappi-mountains-resort.jpg",
            height: "50",
          },
          original: {
            width: "4032",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/17/02/4b/1c/chappi-mountains-resort.jpg",
            height: "3024",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/17/02/4b/1c/chappi-mountains-resort.jpg",
            height: "412",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/17/02/4b/1c/chappi-mountains-resort.jpg",
            height: "188",
          },
        },
        is_blessed: true,
        uploaded_date: "2019-03-31T23:17:35-0400",
        caption: "",
        id: "386026268",
        helpful_votes: "0",
        published_date: "2019-03-31T23:17:35-0400",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      raw_ranking: "3.0762174129486084",
      ranking_geo: "Lac Duong",
      ranking_geo_id: "14759657",
      ranking_position: "7",
      ranking_denominator: "1711",
      ranking_category: "bb",
      ranking: "#7 Best Value of 1,711 places to stay in Nha Trang",
      subcategory_type: "small_hotel",
      subcategory_type_label: "Small Hotel",
      distance: "18.517496440446912",
      distance_string: null,
      bearing: "southwest",
      rating: "4.5",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$25 - $29",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "57b426ab-03c4-483e-815d-5fc7f6fd3d2c",
    },
    {
      location_id: "15011691",
      name: "Misa Guesthouse",
      latitude: "12.25585",
      longitude: "109.09402",
      num_reviews: "0",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Dien Khanh, Khanh Hoa Province",
      photo: {
        images: {
          small: {
            width: "550",
            url: null,
            height: "550",
          },
          thumbnail: {
            width: "550",
            url: null,
            height: "550",
          },
          original: {
            width: "550",
            url: null,
            height: "550",
          },
          large: {
            width: "550",
            url: null,
            height: "550",
          },
          medium: {
            width: "550",
            url: null,
            height: "550",
          },
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      ranking_position: "8",
      ranking_denominator: "1711",
      ranking: "#8 Best Value of 1,711 places to stay in Nha Trang",
      distance: "20.037750020437375",
      distance_string: null,
      bearing: "east",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "6b46b5d4-63d4-4e10-9775-b0b95522173d",
    },
    {
      location_id: "20807217",
      name: "Van Anh Motel",
      latitude: "12.219774",
      longitude: "109.08225",
      num_reviews: "0",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Dien Khanh, Khanh Hoa Province",
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      ranking_position: "9",
      ranking_denominator: "1711",
      ranking: "#9 Best Value of 1,711 places to stay in Nha Trang",
      distance: "20.202401947976522",
      distance_string: null,
      bearing: "southeast",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$12 - $14",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "56cc09e4-ed9c-492b-8757-4e6d8bef6257",
    },
    {
      location_id: "20362856",
      name: "OYO 1015 Bon Mua Hotel",
      latitude: "12.25979",
      longitude: "109.11334",
      num_reviews: "0",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Nha Trang, Khanh Hoa Province",
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      ranking_position: "10",
      ranking_denominator: "1711",
      ranking: "#10 Best Value of 1,711 places to stay in Nha Trang",
      distance: "21.21106684791797",
      distance_string: null,
      bearing: "east",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "53cd6b43-d782-4756-8819-fe8d0cbc58bf",
    },
    {
      location_id: "23268427",
      name: "Nha nghi Huong Thom",
      latitude: "12.151361",
      longitude: "109.07109",
      num_reviews: "0",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Ninh Hoa, Khanh Hoa Province",
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      ranking_position: "11",
      ranking_denominator: "1711",
      ranking: "#11 Best Value of 1,711 places to stay in Nha Trang",
      distance: "22.005794900088333",
      distance_string: null,
      bearing: "southeast",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "e58f193c-34ba-41d6-843b-f3db0cf6f26b",
    },
    {
      location_id: "19617410",
      name: "Ba Ho Eco Resort",
      latitude: "12.390965",
      longitude: "109.138504",
      num_reviews: "0",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Ninh Hoa, Khanh Hoa Province",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/1b/10/bc/6b/caption.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/1b/10/bc/6b/caption.jpg",
            height: "50",
          },
          original: {
            width: "1280",
            url: "https://media-cdn.tripadvisor.com/media/photo-m/1280/1b/10/bc/6b/caption.jpg",
            height: "1280",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-p/1b/10/bc/6b/caption.jpg",
            height: "550",
          },
          medium: {
            width: "450",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/1b/10/bc/6b/caption.jpg",
            height: "450",
          },
        },
        is_blessed: true,
        uploaded_date: "2020-03-02T23:59:41-0500",
        caption:
          "Водопады Ба Хо обязательны к посещению . Ехать с утра и на весь день . Здесь есть все необходимое для отдыха - катамараны , лодочки и тд....ресторан с вкусной и недорогой едой  ! Можно подняться на три  ступени водопадов , в каждом водоём , можно искупаться и сделать пилинг рыбками. Ребята прыгали даже со скал , я не рискнула ))",
        id: "454081643",
        helpful_votes: "0",
        published_date: "2020-03-02T23:59:41-0500",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      ranking_position: "12",
      ranking_denominator: "1711",
      ranking: "#12 Best Value of 1,711 places to stay in Nha Trang",
      distance: "22.35597461500297",
      distance_string: null,
      bearing: "east",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$32 - $44",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "1fc3ee41-f6ed-440d-a4e8-82c160abc3df",
    },
    {
      location_id: "17788780",
      name: "Mega Light Hotel",
      latitude: "12.25718",
      longitude: "109.13179",
      num_reviews: "7",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Nha Trang, Khanh Hoa Province",
      photo: {
        images: {
          small: {
            width: "150",
            url: "https://media-cdn.tripadvisor.com/media/photo-l/1b/50/04/c7/mega-light-hotel.jpg",
            height: "150",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/photo-t/1b/50/04/c7/mega-light-hotel.jpg",
            height: "50",
          },
          original: {
            width: "2880",
            url: "https://media-cdn.tripadvisor.com/media/photo-o/1b/50/04/c7/mega-light-hotel.jpg",
            height: "2025",
          },
          large: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/photo-s/1b/50/04/c7/mega-light-hotel.jpg",
            height: "387",
          },
          medium: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/photo-f/1b/50/04/c7/mega-light-hotel.jpg",
            height: "176",
          },
        },
        is_blessed: true,
        uploaded_date: "2020-05-09T00:47:37-0400",
        caption: "",
        id: "458228935",
        helpful_votes: "0",
        published_date: "2020-05-09T00:47:37-0400",
        user: {
          user_id: null,
          member_id: "0",
          type: "user",
        },
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      raw_ranking: "2.3784210681915283",
      ranking_geo: "Nha Trang",
      ranking_geo_id: "293928",
      ranking_position: "13",
      ranking_denominator: "1711",
      ranking_category: "hotel",
      ranking: "#13 Best Value of 1,711 places to stay in Nha Trang",
      subcategory_type: "hotel",
      subcategory_type_label: "Hotel",
      distance: "22.460704577310636",
      distance_string: null,
      bearing: "east",
      rating: "2.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$10 - $18",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "0f0e1243-5988-4e7c-8f0d-7c046aaa158d",
    },
    {
      location_id: "21106942",
      name: "OYO 995 Tan Thanh Dat Hotel",
      latitude: "12.47471",
      longitude: "109.12265",
      num_reviews: "0",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Nha Trang, Khanh Hoa Province",
      photo: {
        images: {
          small: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/24/f0/1f/93/caption.jpg",
            height: "137",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/24/f0/1f/93/caption.jpg",
            height: "50",
          },
          original: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/24/f0/1f/93/caption.jpg",
            height: "460",
          },
          large: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/24/f0/1f/93/caption.jpg",
            height: "460",
          },
          medium: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/24/f0/1f/93/caption.jpg",
            height: "301",
          },
        },
        is_blessed: true,
        uploaded_date: "2022-07-25T00:37:44-0400",
        caption: "",
        id: "619716499",
        helpful_votes: "0",
        published_date: "2022-07-25T00:37:44-0400",
        user: null,
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      ranking_position: "14",
      ranking_denominator: "1711",
      ranking: "#14 Best Value of 1,711 places to stay in Nha Trang",
      distance: "22.92105530894745",
      distance_string: null,
      bearing: "northeast",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "c9b1e020-922a-41f8-8580-709db3d83be3",
    },
    {
      location_id: "293928",
      ad_position: "inline2",
      ad_size: "8X8",
      doubleclick_zone: "as.vietnam.khanh_hoa.nha_trang",
      ancestors: [
        {
          subcategory: [
            {
              key: "province",
              name: "Province",
            },
          ],
          name: "Khanh Hoa Province",
          abbrv: null,
          location_id: "1184689",
        },
        {
          subcategory: [
            {
              key: "country",
              name: "Country",
            },
          ],
          name: "Vietnam",
          abbrv: null,
          location_id: "293921",
        },
      ],
      detail: "0",
      page_type: "hotels",
      mob_ptype: "app_hotels",
    },
    {
      location_id: "17707459",
      name: "Casa Blanca Villas",
      latitude: "12.259272",
      longitude: "109.1431",
      num_reviews: "1",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Nha Trang, Khanh Hoa Province",
      photo: {
        images: {
          small: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/29/46/a9/a0/caption.jpg",
            height: "137",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/29/46/a9/a0/caption.jpg",
            height: "50",
          },
          original: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/29/46/a9/a0/caption.jpg",
            height: "460",
          },
          large: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/29/46/a9/a0/caption.jpg",
            height: "460",
          },
          medium: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/29/46/a9/a0/caption.jpg",
            height: "301",
          },
        },
        is_blessed: true,
        uploaded_date: "2023-05-25T01:53:07-0400",
        caption: "",
        id: "692496800",
        helpful_votes: "0",
        published_date: "2023-05-25T01:53:07-0400",
        user: null,
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      raw_ranking: "3.042398452758789",
      ranking_geo: "Nha Trang",
      ranking_geo_id: "293928",
      ranking_position: "15",
      ranking_denominator: "1711",
      ranking_category: "bb",
      ranking: "#15 Best Value of 1,711 places to stay in Nha Trang",
      subcategory_type: "guest_house",
      subcategory_type_label: "Guest house",
      distance: "23.16180801461108",
      distance_string: null,
      bearing: "east",
      rating: "5.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "$$$$",
      price: "$453 - $675",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "9507e7c2-3182-4555-9f08-52d4a55edc34",
    },
    {
      location_id: "15321078",
      name: "Diagon Alley Homestay",
      latitude: "12.260297",
      longitude: "109.14451",
      num_reviews: "0",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Nha Trang, Khanh Hoa Province",
      photo: {
        images: {
          small: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/19/b6/f5/aa/2715551.jpg",
            height: "137",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/19/b6/f5/aa/2715551.jpg",
            height: "50",
          },
          original: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/19/b6/f5/aa/2715551.jpg",
            height: "460",
          },
          large: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/19/b6/f5/aa/2715551.jpg",
            height: "460",
          },
          medium: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/19/b6/f5/aa/2715551.jpg",
            height: "301",
          },
        },
        is_blessed: true,
        uploaded_date: "2019-10-17T19:16:45-0400",
        caption: "Diagon Alley Homestay",
        id: "431420842",
        helpful_votes: "0",
        published_date: "2019-10-17T19:16:45-0400",
        user: null,
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      ranking_position: "16",
      ranking_denominator: "1711",
      ranking: "#16 Best Value of 1,711 places to stay in Nha Trang",
      distance: "23.236559140207984",
      distance_string: null,
      bearing: "east",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "a823a8a3-9beb-435b-b179-8bc1ddde4aa0",
    },
    {
      location_id: "21504434",
      name: "Bao My Hotel",
      latitude: "12.486257",
      longitude: "109.12736",
      num_reviews: "0",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Ninh Hiep, Ninh Hoa, Khanh Hoa Province",
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      ranking_position: "17",
      ranking_denominator: "1711",
      ranking: "#17 Best Value of 1,711 places to stay in Nha Trang",
      distance: "23.537567114872367",
      distance_string: null,
      bearing: "northeast",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "bb386bb4-44f4-4c17-a570-263b0570f0ec",
    },
    {
      location_id: "12791381",
      name: "Anh Hao Hotel",
      latitude: "12.492512",
      longitude: "109.125656",
      num_reviews: "1",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Ninh Hoa, Khanh Hoa Province",
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      raw_ranking: "3.020765781402588",
      ranking_geo: "Ninh Hoa",
      ranking_geo_id: "12920594",
      ranking_position: "18",
      ranking_denominator: "1711",
      ranking_category: "bb",
      ranking: "#18 Best Value of 1,711 places to stay in Nha Trang",
      subcategory_type: "inn",
      subcategory_type_label: "Inn",
      distance: "23.61926745486276",
      distance_string: null,
      bearing: "northeast",
      rating: "5.0",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$10 - $11",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "26c7011f-4634-4401-97ca-940c4ca8d211",
    },
    {
      location_id: "15353817",
      name: "Homestay Da Blah",
      latitude: "12.105029",
      longitude: "108.55508",
      num_reviews: "0",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Lac Duong, Lam Dong Province",
      photo: {
        images: {
          small: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/1b/5d/12/0f/3936219.jpg",
            height: "137",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/1b/5d/12/0f/3936219.jpg",
            height: "50",
          },
          original: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/1b/5d/12/0f/3936219.jpg",
            height: "460",
          },
          large: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/1b/5d/12/0f/3936219.jpg",
            height: "460",
          },
          medium: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/1b/5d/12/0f/3936219.jpg",
            height: "301",
          },
        },
        is_blessed: true,
        uploaded_date: "2020-05-30T23:16:35-0400",
        caption: "Homestay Da Blah",
        id: "459084303",
        helpful_votes: "0",
        published_date: "2020-05-30T23:16:35-0400",
        user: null,
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      ranking_position: "19",
      ranking_denominator: "1711",
      ranking: "#19 Best Value of 1,711 places to stay in Nha Trang",
      distance: "23.896876731770504",
      distance_string: null,
      bearing: "southwest",
      is_closed: false,
      is_long_closed: false,
      price_level: "$",
      price: "$12",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "9dce6245-e2f4-4df9-a227-4c4b433abb2d",
    },
    {
      location_id: "18261033",
      name: "Nha Khach Vuon Quoc Gia Bidoup - Nui Ba",
      latitude: "12.105029",
      longitude: "108.55508",
      num_reviews: "0",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Da Nhim, Lam Dong Province",
      photo: {
        images: {
          small: {
            width: "250",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-f/19/a8/f1/5c/4892278.jpg",
            height: "137",
          },
          thumbnail: {
            width: "50",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-t/19/a8/f1/5c/4892278.jpg",
            height: "50",
          },
          original: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/19/a8/f1/5c/4892278.jpg",
            height: "460",
          },
          large: {
            width: "840",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-o/19/a8/f1/5c/4892278.jpg",
            height: "460",
          },
          medium: {
            width: "550",
            url: "https://media-cdn.tripadvisor.com/media/partner/bookingcom/photo-s/19/a8/f1/5c/4892278.jpg",
            height: "301",
          },
        },
        is_blessed: true,
        uploaded_date: "2019-10-17T05:35:54-0400",
        caption: "Nha Khach Vuon Quoc Gia Bidoup - Nui Ba",
        id: "430502236",
        helpful_votes: "0",
        published_date: "2019-10-17T05:35:54-0400",
        user: null,
      },
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      ranking_position: "20",
      ranking_denominator: "1711",
      ranking: "#20 Best Value of 1,711 places to stay in Nha Trang",
      distance: "23.896876731770504",
      distance_string: null,
      bearing: "southwest",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "49ab2ac1-98db-4c0c-b45f-0f5f7e5231c9",
    },
    {
      location_id: "17537513",
      name: "Junglebeach",
      latitude: "12.49512",
      longitude: "109.13291",
      num_reviews: "0",
      timezone: "Asia/Ho_Chi_Minh",
      location_string: "Ninh Hoa, Khanh Hoa Province",
      awards: [],
      preferred_map_engine: "default",
      autobroaden_type: "category_integrated",
      autobroaden_label: "Nha Trang Places to Stay",
      ranking_position: "21",
      ranking_denominator: "1711",
      ranking: "#21 Best Value of 1,711 places to stay in Nha Trang",
      distance: "24.13888025704297",
      distance_string: null,
      bearing: "northeast",
      is_closed: false,
      is_long_closed: false,
      price_level: "",
      hotel_class: "0.0",
      business_listings: {
        desktop_contacts: [],
        mobile_contacts: [],
      },
      special_offers: {
        desktop: [],
        mobile: [],
      },
      listing_key: "c50f4a85-0c82-4cfb-b22f-bbea44704167",
    },
  ],
};
